Repository TeamMiso/Miso_Android_v2, pull requests merged in 2023-12, with the labels that each got.

#5 🔀 :: (#2) - ci test
  .github/workflows/miso_android_ci.yml
Labels: ⚙ Setting, 0️⃣ Priority: Critical

#8 🔀 :: (#7) - di setting
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  design-system/build.gradle.kts
  di/build.gradle.kts
  di/src/main/java/com/miso/miso_android_v2/MisoApplication.kt
  domain/build.gradle.kts
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/miso/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/ui/theme/Color.kt
  presentation/src/main/java/com/miso/presentation/ui/ui/theme/Theme.kt
  presentation/src/main/java/com/miso/presentation/ui/ui/theme/Type.kt
  presentation/src/main/res/values/strings.xml
  presentation/src/main/res/values/themes.xml
Labels: ⚙ Setting, 0️⃣ Priority: Critical

#10 🔀 :: (#9) - design system setting
  design-system/src/main/java/com/miso/design_system/theme/ColorTheme.kt
  design-system/src/main/java/com/miso/design_system/theme/MisoTheme.kt
  design-system/src/main/java/com/miso/design_system/theme/MisoTypography.kt
Labels: ⚙ Setting, 1️⃣ Priority: High

#12 🔀 :: (#11) - publishing login
  design-system/src/main/java/com/miso/design_system/component/button/MisoButton.kt
  design-system/src/main/java/com/miso/design_system/component/textfield/MisoTextField.kt
  design-system/src/main/java/com/miso/design_system/icon/MisoIcon.kt
  design-system/src/main/java/com/miso/design_system/theme/MisoTypography.kt
  design-system/src/main/res/drawable/ic_delete_btn.xml
  design-system/src/main/res/drawable/ic_visibility.xml
  design-system/src/main/res/drawable/ic_visibility_off.xml
  di/src/main/AndroidManifest.xml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/miso/presentation/ui/.gitkeep
  presentation/src/main/java/com/miso/presentation/ui/MainActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/base/BaseActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/login/component/LoginDividerAndText.kt
  presentation/src/main/java/com/miso/presentation/ui/login/component/MisoSubTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/login/component/MisoTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/login/component/MoveSignUpText.kt
  presentation/src/main/java/com/miso/presentation/ui/login/screen/LoginScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/util/keyboardAsState.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#14 🔀 :: (#13) - publishing splash
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  design-system/src/main/res/drawable/ic_miso.xml
  design-system/src/main/res/drawable/ic_miso_inset.xml
  di/src/main/AndroidManifest.xml
  di/src/main/res/values-v31/splash.xml
  presentation/build.gradle.kts
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#18 🔀 :: (#17) - write the logic sign up
  data/src/main/java/com/miso/data/remote/.gitkeep
  data/src/main/java/com/miso/data/remote/api/.gitkeep
  data/src/main/java/com/miso/data/remote/api/AuthAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/.gitkeep
  data/src/main/java/com/miso/data/remote/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/.gitkeep
  data/src/main/java/com/miso/data/remote/dto/auth/request/AuthSignUpRequest.kt
  data/src/main/java/com/miso/data/repository/.gitkeep
  data/src/main/java/com/miso/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/miso/data/util/.gitkeep
  data/src/main/java/com/miso/data/util/MisoApiHandler.kt
  di/build.gradle.kts
  di/src/main/AndroidManifest.xml
  di/src/main/java/com/miso/miso_android_v2/module/.gitkeep
  di/src/main/java/com/miso/miso_android_v2/module/NetworkModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RemoteDatasourceModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RepositoryModule.kt
  domain/src/main/java/com/miso/domain/exception/.gitkeep
  domain/src/main/java/com/miso/domain/exception/HttpException.kt
  domain/src/main/java/com/miso/domain/exception/InternetException.kt
  domain/src/main/java/com/miso/domain/exception/TokenExpirationException.kt
  domain/src/main/java/com/miso/domain/model/.gitkeep
  domain/src/main/java/com/miso/domain/model/auth/request/AuthSignUpRequestModel.kt
  domain/src/main/java/com/miso/domain/repository/.gitkeep
  domain/src/main/java/com/miso/domain/repository/AuthRepository.kt
  domain/src/main/java/com/miso/domain/usecase/.gitkeep
  domain/src/main/java/com/miso/domain/usecase/auth/AuthSignUpUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/sign_up/screen/SignUpScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/.gitkeep
  presentation/src/main/java/com/miso/presentation/viewmodel/AuthViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/util/Event.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/util/errorHandling.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#20 🔀 :: (#19) - write the logic verification
  data/src/main/java/com/miso/data/remote/api/EmailAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/email/EmailDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/email/EmailDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/email/request/EmailRequest.kt
  data/src/main/java/com/miso/data/repository/EmailRepositoryImpl.kt
  di/src/main/java/com/miso/miso_android_v2/module/NetworkModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RemoteDatasourceModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RepositoryModule.kt
  domain/src/main/java/com/miso/domain/model/email/request/EmailRequestModel.kt
  domain/src/main/java/com/miso/domain/repository/EmailRepository.kt
  domain/src/main/java/com/miso/domain/usecase/email/EmailUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/sign_up/screen/VerificationScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/EmailViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#24 🔀 :: (#23) - write the logic auto login and save token
  data/build.gradle.kts
  data/src/main/java/com/miso/data/local/.gitkeep
  data/src/main/java/com/miso/data/local/datasource/auth/LocalAuthDataSource.kt
  data/src/main/java/com/miso/data/local/datasource/auth/LocalAuthDataSourceImpl.kt
  data/src/main/java/com/miso/data/local/key/AuthPreferenceKey.kt
  data/src/main/java/com/miso/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/miso/data/util/AuthInterceptor.kt
  data/src/main/java/com/miso/data/util/DataFormatter.kt
  design-system/src/main/java/com/miso/design_system/component/textfield/MisoTextField.kt
  di/src/main/java/com/miso/miso_android_v2/module/DataStoreModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/LocalDataSourceModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/NetworkModule.kt
  domain/src/main/java/com/miso/domain/repository/AuthRepository.kt
  domain/src/main/java/com/miso/domain/usecase/auth/SaveTokenUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/login/screen/LoginScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/AuthViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#28 🔀 :: (#25) - publishing search
  design-system/build.gradle.kts
  design-system/src/main/java/com/miso/design_system/component/bottombar/MisoBottomNavigationBar.kt
  design-system/src/main/java/com/miso/design_system/component/chip/MisoChip.kt
  design-system/src/main/java/com/miso/design_system/component/text/MisoLogoTitleText.kt
  design-system/src/main/java/com/miso/design_system/component/textfield/MisoTextField.kt
  design-system/src/main/java/com/miso/design_system/icon/MisoIcon.kt
  design-system/src/main/res/drawable/ic_camera.xml
  design-system/src/main/res/drawable/ic_hide_button.xml
  design-system/src/main/res/drawable/ic_inquiry.xml
  design-system/src/main/res/drawable/ic_inquiry_click.xml
  design-system/src/main/res/drawable/ic_menu.xml
  design-system/src/main/res/drawable/ic_miso_color.xml
  design-system/src/main/res/drawable/ic_nav_background.xml
  design-system/src/main/res/drawable/ic_search.xml
  design-system/src/main/res/drawable/ic_search_click.xml
  design-system/src/main/res/drawable/ic_setting.xml
  design-system/src/main/res/drawable/ic_setting_click.xml
  design-system/src/main/res/drawable/ic_shop.xml
  design-system/src/main/res/drawable/ic_shop_click.xml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/SearchHistoryList.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/SearchHistoryListItem.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/SearchHistoryTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/TodayEnvironmentTipComponent.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#27 🔀 :: (#26) - publishing camera
  .idea/inspectionProfiles/Project_Default.xml
  design-system/src/main/res/drawable/ic_camera_capure_button.xml
  design-system/src/main/res/drawable/ic_camera_flash_off_button.xml
  design-system/src/main/res/drawable/ic_camera_flash_on_button.xml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraButton.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraPreview.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraScreen.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#31 🔀 :: (#30) - write the logic search
  data/src/main/java/com/miso/data/remote/api/RecyclablesAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/recyclables/RecyclablesDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/recyclables/RecyclablesDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/recyclables/response/SearchResponse.kt
  data/src/main/java/com/miso/data/repository/RecyclablesRepositoryImpl.kt
  design-system/src/main/java/com/miso/design_system/component/textfield/MisoTextField.kt
  di/src/main/java/com/miso/miso_android_v2/module/NetworkModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RemoteDatasourceModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RepositoryModule.kt
  domain/src/main/java/com/miso/domain/model/recyclables/response/SearchResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/RecyclablesRepository.kt
  domain/src/main/java/com/miso/domain/usecase/recyclables/SearchUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/SearchTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/RecyclablesViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#33 🔀 :: (#32) - publishing searchable list
  design-system/src/main/java/com/miso/design_system/component/bottombar/MisoBottomNavigationBar.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/SearchList.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/SearchListItem.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchableListScreen.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#35 🔀 :: (#34) - write the logic searchable list
  data/src/main/java/com/miso/data/remote/api/RecyclablesAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/recyclables/RecyclablesDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/recyclables/RecyclablesDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/recyclables/response/SearchableListResponse.kt
  data/src/main/java/com/miso/data/repository/RecyclablesRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/model/recyclables/response/SearchableListResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/RecyclablesRepository.kt
  domain/src/main/java/com/miso/domain/usecase/recyclables/SearchableListUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/SearchList.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchableListScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/RecyclablesViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#37 🔀 :: (#29) permission dialog
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/permissiondialog/PermissionDialog.kt
  presentation/src/main/java/com/miso/presentation/ui/util/PermissionDescriptionProvider.kt
  presentation/src/main/java/com/miso/presentation/ui/util/PermissionHandler.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#39 🔀 :: (#36) - publishing result
  presentation/src/main/java/com/miso/presentation/ui/result/component/RecycleCautionText.kt
  presentation/src/main/java/com/miso/presentation/ui/result/component/RecycleContentText.kt
  presentation/src/main/java/com/miso/presentation/ui/result/component/RecycleImage.kt
  presentation/src/main/java/com/miso/presentation/ui/result/component/RecycleMethodText.kt
  presentation/src/main/java/com/miso/presentation/ui/result/component/RecycleTipText.kt
  presentation/src/main/java/com/miso/presentation/ui/result/component/ResultRecyclablesTypeText.kt
  presentation/src/main/java/com/miso/presentation/ui/result/component/ResultSubTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/result/component/ResultTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/result/screen/ResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
Labels: 🎨 Publishing, 0️⃣ Priority: Critical

#41 🔀 :: (#40) - write the logic result
  data/src/main/java/com/miso/data/remote/api/RecyclablesAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/recyclables/RecyclablesDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/recyclables/RecyclablesDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/recyclables/response/ResultResponse.kt
  data/src/main/java/com/miso/data/repository/RecyclablesRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/model/recyclables/response/ResultResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/RecyclablesRepository.kt
  domain/src/main/java/com/miso/domain/usecase/recyclables/ResultUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/result/screen/ResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/RecyclablesViewModel.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#42 🔀 :: (#38) - publishing camera result
  .idea/kotlinScripting.xml
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraResultBottomButton.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraResultPreview.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
Labels: 🎨 Publishing, 0️⃣ Priority: Critical

#45 🔀 :: (#43) - write the logic search history
  data/src/main/java/com/miso/data/local/datasource/recyclables/LocalRecyclablesDataSource.kt
  data/src/main/java/com/miso/data/local/datasource/recyclables/LocalRecyclablesDataSourceImpl.kt
  data/src/main/java/com/miso/data/local/key/AuthPreferenceKey.kt
  data/src/main/java/com/miso/data/local/key/RecyclablesPreferenceKey.kt
  data/src/main/java/com/miso/data/repository/RecyclablesRepositoryImpl.kt
  di/src/main/java/com/miso/miso_android_v2/module/LocalDataSourceModule.kt
  domain/src/main/java/com/miso/domain/repository/RecyclablesRepository.kt
  domain/src/main/java/com/miso/domain/usecase/recyclables/GetSearchHistoryUseCase.kt
  domain/src/main/java/com/miso/domain/usecase/recyclables/SaveSearchHistoryUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/SearchList.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/SearchListItem.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/TodayEnvironmentTipComponent.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchableListScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/RecyclablesViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#46 🔀 :: (#44) implementing camera features
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraPreview.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraResultPreview.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/state/CapturedState.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/util/CapturePhoto.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/CameraViewModel.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#49 🔀 :: (#48) - camera flash
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraButton.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraPreview.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraScreen.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#51 🔀 :: (#50) - camera navigation features
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraScreen.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#53 🔀 :: (#52) - publishing shop
  design-system/src/main/java/com/miso/design_system/component/chip/MisoChip.kt
  design-system/src/main/res/drawable/ic_purchase.xml
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/ShopList.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/ShopListItem.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopScreen.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#56 🔀 :: (#54) - write the logic shop
  data/src/main/java/com/miso/data/remote/api/ShopAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/shop/ShopDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/shop/ShopDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/shop/response/ShopListResponse.kt
  data/src/main/java/com/miso/data/repository/ShopRepositoryImpl.kt
  di/src/main/java/com/miso/miso_android_v2/module/NetworkModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RemoteDatasourceModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RepositoryModule.kt
  domain/src/main/java/com/miso/domain/model/shop/response/ShopListResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/ShopRepository.kt
  domain/src/main/java/com/miso/domain/usecase/shop/ShopListUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/login/screen/LoginScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/NoSearchText.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchableListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/ShopList.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/ShopListItem.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/AuthViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/EmailViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/RecyclablesViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/ShopViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/util/Event.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/util/errorHandling.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#58 🔀 :: (#47) - camera navigation features
  data/src/main/java/com/miso/data/remote/api/RecyclablesAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/recyclables/RecyclablesDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/recyclables/RecyclablesDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/recyclables/response/AiListResponse.kt
  data/src/main/java/com/miso/data/repository/RecyclablesRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/model/recyclables/response/AiListResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/RecyclablesRepository.kt
  domain/src/main/java/com/miso/domain/usecase/recyclables/GetAiListUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraPreview.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraResultBottomButton.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraResultPreview.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/CameraViewModel.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#59 🔀 :: (#55) - link firebase
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/ProjectProperties.kt
  di/google-services.json
Labels: ✨ Feature, 1️⃣ Priority: High

#61 🔀 :: (#57) - write the logic user
  data/src/main/java/com/miso/data/remote/api/UserAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/user/UserDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/user/UserDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/user/response/PointResponse.kt
  data/src/main/java/com/miso/data/remote/dto/user/response/UserInfoResponse.kt
  data/src/main/java/com/miso/data/repository/UserRepositoryImpl.kt
  di/src/main/java/com/miso/miso_android_v2/module/NetworkModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RemoteDatasourceModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RepositoryModule.kt
  domain/src/main/java/com/miso/domain/model/user/response/PointResponseModel.kt
  domain/src/main/java/com/miso/domain/model/user/response/UserInfoResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/UserRepository.kt
  domain/src/main/java/com/miso/domain/usecase/user/GetPointUseCase.kt
  domain/src/main/java/com/miso/domain/usecase/user/GetUserInfoUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/ShopViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/UserViewModel.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#63 🔀 :: (#62) - publishing shop detail
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/DetailContentText.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/DetailImage.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/ShopList.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/UserPointText.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopDetailScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopScreen.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#65 🔀 :: (#64) - write the logic shop detail
  data/src/main/java/com/miso/data/remote/api/ShopAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/shop/ShopDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/shop/ShopDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/shop/response/ShopListDetailResponse.kt
  data/src/main/java/com/miso/data/repository/ShopRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/model/shop/response/ShopListDetailResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/ShopRepository.kt
  domain/src/main/java/com/miso/domain/usecase/shop/ShopListDetailUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/DetailImage.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/ShopListItem.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopDetailScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/util/formatNumber.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/ShopViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#67 🔀 :: (#60) - ai result search
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  design-system/build.gradle.kts
  design-system/src/main/java/com/miso/design_system/component/lottie/MisoLoadingLottie.kt
  design-system/src/main/res/raw/flow_3.json
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#69 🔀 :: (#68) inquiry page publishing
  design-system/src/main/java/com/miso/design_system/theme/MisoTypography.kt
  design-system/src/main/res/drawable/ic_inquiry_add_image.xml
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryImageButton.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryTextTextField.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryTitleTextField.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryTopBar.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryScreen.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#71 🔀 :: (#70) camera publishing modify
  .idea/kotlinScripting.xml
  design-system/src/main/java/com/miso/design_system/component/lottie/MisoLoadingLottie.kt
  design-system/src/main/res/raw/flow_3.json
  design-system/src/main/res/raw/miso_loading.json
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraButton.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraResultBottomButton.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraResultPreview.kt
Labels: ⚡️ Simple, 1️⃣ Priority: High

#73 🔀 :: (#72) - inquiry bottom sheet publishing
  design-system/src/main/java/com/miso/design_system/component/bottomsheet/MisoBottomSheet.kt
  design-system/src/main/java/com/miso/design_system/icon/MisoIcon.kt
  design-system/src/main/res/drawable/ic_camera_bottm_sheet.xml
  design-system/src/main/res/drawable/ic_gallery_bottom_sheet.xml
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryTopBar.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/bottomsheet/SelectPhotoPathBottomSheet.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/bottomsheet/SelectPhotoPathBottomSheetComponent.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#75 🔀 :: (#66) - write the logic purchase
  data/src/main/java/com/miso/data/remote/api/PurchaseAPI.kt
  data/src/main/java/com/miso/data/remote/api/UserAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/purchase/PurchaseDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/purchase/PurchaseDataSourceImpl.kt
  data/src/main/java/com/miso/data/repository/PurchaseRepositoryImpl.kt
  design-system/src/main/java/com/miso/design_system/component/button/MisoButton.kt
  design-system/src/main/java/com/miso/design_system/component/dialog/MisoDialog.kt
  design-system/src/main/java/com/miso/design_system/theme/ColorTheme.kt
  design-system/src/main/java/com/miso/design_system/theme/color/LightColor.kt
  di/src/main/java/com/miso/miso_android_v2/module/NetworkModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RemoteDatasourceModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RepositoryModule.kt
  domain/src/main/java/com/miso/domain/repository/PurchaseRepository.kt
  domain/src/main/java/com/miso/domain/usecase/purchase/PurchaseUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopDetailScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/PurchaseViewModel.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#77 🔀 :: (#74) - add inquiry logic
  data/src/main/java/com/miso/data/remote/api/InquiryAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/inquiry/request/InquiryRequest.kt
  data/src/main/java/com/miso/data/repository/InquiryRepositoryImpl.kt
  di/src/main/java/com/miso/miso_android_v2/module/NetworkModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RemoteDatasourceModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RepositoryModule.kt
  domain/src/main/java/com/miso/domain/model/inquiry/response/InquiryRequestModel.kt
  domain/src/main/java/com/miso/domain/repository/InquiryRepository.kt
  domain/src/main/java/com/miso/domain/usecase/inquiry/RequestInquiryUseCase.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryContentTextField.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryImageButton.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryTitleTextField.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryTopBar.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/bottomsheet/SelectPhotoPathBottomSheet.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/state/ByteArrayState.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/util/GetMultipartFile.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/CameraViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#79 (#76) - publishing setting
  design-system/src/main/java/com/miso/design_system/component/dialog/MisoDialog.kt
  design-system/src/main/java/com/miso/design_system/component/toggle/MisoToggle.kt
  design-system/src/main/java/com/miso/design_system/icon/MisoIcon.kt
  design-system/src/main/res/drawable/ic_logout.xml
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/setting/component/EmailText.kt
  presentation/src/main/java/com/miso/presentation/ui/setting/component/LogoutButton.kt
  presentation/src/main/java/com/miso/presentation/ui/setting/component/PushNotificationText.kt
  presentation/src/main/java/com/miso/presentation/ui/setting/screen/SettingScreen.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#81 🔀 :: (#78) - camera result page publishing
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/result/CameraRecycleCautionText.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/result/CameraRecycleContentText.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/result/CameraRecycleImage.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/result/CameraRecycleMethodText.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/result/CameraRecycleTipText.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/result/CameraResultRecyclablesTypeText.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/result/CameraResultSubTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/result/CameraResultTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/result/CameraWrongAnswerButton.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraCaptureResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/result/screen/ResultScreen.kt
Labels: 🎨 Publishing, 0️⃣ Priority: Critical

#83 🔀 :: (#80) - write the logic logout
  data/src/main/java/com/miso/data/remote/api/AuthAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/auth/AuthDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/miso/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/miso/data/repository/RecyclablesRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/repository/AuthRepository.kt
  domain/src/main/java/com/miso/domain/repository/RecyclablesRepository.kt
  domain/src/main/java/com/miso/domain/usecase/auth/DeleteTokenUseCase.kt
  domain/src/main/java/com/miso/domain/usecase/auth/LogoutUseCase.kt
  domain/src/main/java/com/miso/domain/usecase/recyclables/DeleteSearchHistoryUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/setting/screen/SettingScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/AuthViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/CameraViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/EmailViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#87 🔀 :: (#82) - write camera result logic
  data/src/main/java/com/miso/data/remote/api/UserAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/user/UserDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/user/UserDataSourceImpl.kt
  data/src/main/java/com/miso/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/repository/UserRepository.kt
  domain/src/main/java/com/miso/domain/usecase/user/GivePointUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraCaptureResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/CameraViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/UserViewModel.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#89 🔀 :: (#86) - write the logic inquiry list
  data/src/main/java/com/miso/data/remote/api/InquiryAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/inquiry/response/InquiryListResponse.kt
  data/src/main/java/com/miso/data/repository/InquiryRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/model/inquiry/request/InquiryRequestModel.kt
  domain/src/main/java/com/miso/domain/model/inquiry/response/InquiryListResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/InquiryRepository.kt
  domain/src/main/java/com/miso/domain/usecase/inquiry/GetInquiryListAllUseCase.kt
  domain/src/main/java/com/miso/domain/usecase/inquiry/GetInquiryListUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryList.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/util/extention.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#92 🔀 :: (#88) - publishing inquiry answer
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryAnswerStateText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryDateText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryTopBar.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryAnswerScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryScreen.kt
Labels: 🎨 Publishing, 0️⃣ Priority: Critical

#91 🔀 :: (#90) - publishing purchase list
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/PurchaseList.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/PurchaseListItem.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/PurchaseListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopScreen.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#96 🔀 :: (#94) - write the logic purchase list
  data/src/main/java/com/miso/data/remote/api/PurchaseAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/purchase/PurchaseDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/purchase/PurchaseDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/purchase/response/PurchaseListResponse.kt
  data/src/main/java/com/miso/data/repository/PurchaseRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/model/purchase/response/PurchaseListResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/PurchaseRepository.kt
  domain/src/main/java/com/miso/domain/usecase/purchase/GetPurchaseListUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/PurchaseList.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/PurchaseListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopDetailScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/PurchaseViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#98 🔀 :: (#97) - publishing inquiry list detail
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryListDetailContentText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryListDetailContentTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryListDetailImage.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryListDetailStatusText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListDetailScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/result/screen/ResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#101 🔀 :: (#100) - write the logic inquiry list detail
  data/src/main/java/com/miso/data/remote/api/InquiryAPI.kt
  data/src/main/java/com/miso/data/remote/api/NotificationAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/datasource/notification/NotificationDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/notification/NotificationDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/inquiry/response/InquiryListDetailResponse.kt
  data/src/main/java/com/miso/data/remote/dto/notification/response/AnswerResponse.kt
  data/src/main/java/com/miso/data/repository/InquiryRepositoryImpl.kt
  data/src/main/java/com/miso/data/repository/NotificationRepositoryImpl.kt
  di/src/main/java/com/miso/miso_android_v2/module/NetworkModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RemoteDatasourceModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RepositoryModule.kt
  domain/src/main/java/com/miso/domain/model/inquiry/response/InquiryListDetailResponseModel.kt
  domain/src/main/java/com/miso/domain/model/notification/response/AnswerResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/InquiryRepository.kt
  domain/src/main/java/com/miso/domain/repository/NotificationRepository.kt
  domain/src/main/java/com/miso/domain/usecase/inquiry/GetInquiryListDetailUseCase.kt
  domain/src/main/java/com/miso/domain/usecase/notification/GetAnswerUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListDetailScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/util/extention.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/NotificationViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#99 🔀 :: (#95) refactoring permission dialog
  design-system/src/main/res/drawable/ic_permission_gallery.xml
  design-system/src/main/res/drawable/ic_premission_camera.xml
  presentation/src/main/java/com/miso/presentation/ui/permissiondialog/PermissionDialog.kt
  presentation/src/main/java/com/miso/presentation/ui/util/PermissionDescriptionProvider.kt
Labels: ✨ Feature, 🎨 Publishing, 0️⃣ Priority: Critical

#103 🔀 :: (#102) - error handling sign up
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/login/LoginActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/sign_up/screen/VerificationScreen.kt
Labels: 🔨 Refector, 0️⃣ Priority: Critical

#106 🔀 :: (#105) - camera redundant execution
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/CameraViewModel.kt
Labels: 🐞 Bug, 0️⃣ Priority: Critical

#109 🔀 :: (#108) - modify answer parameters
  data/src/main/java/com/miso/data/remote/dto/notification/response/AnswerResponse.kt
  domain/src/main/java/com/miso/domain/model/notification/response/AnswerResponseModel.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListDetailScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/NotificationViewModel.kt
Labels: 🔨 Refector, 1️⃣ Priority: High

#112 🔀 :: (#110) - manipulating notification permission
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/setting/component/EmailText.kt
  presentation/src/main/java/com/miso/presentation/ui/setting/screen/SettingScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/PurchaseListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopScreen.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#115 🔀 :: (#114) - publishing today environment tip
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/TodayEnvironmentTipContentText.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/TodayEnvironmentTipImage.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/TodayEnvironmentTipTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/TodayEnvironmentTipScreen.kt
Labels: 🎨 Publishing, 2️⃣ Priortiy: Medium

#113 🔀 :: (#111) camera result inconsistency
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraResultInconsistencyItem.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraResultInconsistencyText.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/component/result/CameraRecycleImage.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraCaptureResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultInconsistencyScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/CameraViewModel.kt
Labels: ✨ Feature, 🎨 Publishing, 0️⃣ Priority: Critical

#117 🔀 :: (#116) - write the logic today environment tip
  data/src/main/java/com/miso/data/remote/api/EnvironmentAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/environment/EnvironmentDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/environment/EnvironmentDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/environment/response/EnvironmentResponse.kt
  data/src/main/java/com/miso/data/repository/EnvironmentRepositoryImpl.kt
  di/src/main/java/com/miso/miso_android_v2/module/NetworkModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RemoteDatasourceModule.kt
  di/src/main/java/com/miso/miso_android_v2/module/RepositoryModule.kt
  domain/src/main/java/com/miso/domain/model/environment/response/EnvironmentResponseModel.kt
  domain/src/main/java/com/miso/domain/repository/EnvironmentRepository.kt
  domain/src/main/java/com/miso/domain/usecase/environment/GetEnvironmentUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/TodayEnvironmentTipScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/EnvironmentViewModel.kt
Labels: ✨ Feature, 2️⃣ Priortiy: Medium

#120 🔀 :: (#118) - publishing send answer
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryContentTextField.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryDateText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryListDetailImage.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryListDetailStatusText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryTopBar.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryAnswerScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListDetailScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/TodayEnvironmentTipImage.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#122 🔀 :: (#121) - write the logic send answer
  data/src/main/java/com/miso/data/remote/api/InquiryAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSourceImpl.kt
  data/src/main/java/com/miso/data/remote/dto/inquiry/request/AnswerRequest.kt
  data/src/main/java/com/miso/data/repository/InquiryRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/model/inquiry/request/AnswerRequestModel.kt
  domain/src/main/java/com/miso/domain/repository/InquiryRepository.kt
  domain/src/main/java/com/miso/domain/usecase/inquiry/SendAnswerUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryListDetailStatusText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryAnswerScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/TodayEnvironmentTipComponent.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#123 🔀 :: (#119) inquiry image delete and default image set
  design-system/src/main/res/drawable/ic_delete_image_button.xml
  presentation/src/main/java/com/miso/presentation/ui/camera/CameraActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraCaptureResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryDeleteImageButton.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryImageButton.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/bottomsheet/SelectPhotoPathBottomSheet.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/bottomsheet/SelectPhotoPathBottomSheetComponent.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/dialog/InquiryDialog.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/CameraViewModel.kt
Labels: ✨ Feature, 🎨 Publishing, 0️⃣ Priority: Critical

#126 🔀 :: (#125) - publishing inquiry answer dialog
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryAnswerScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
Labels: 🎨 Publishing, ⚡️ Simple, 3️⃣ Priority: Low

#128 change the content of the inquiry answer dialog
  design-system/src/main/java/com/miso/design_system/component/dialog/MisoDialog.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryAnswerScreen.kt
Labels: ⚡️ Simple, 3️⃣ Priority: Low

#130 🔀 :: (#129) - delete locally stored tokens at token expiration
  data/src/main/java/com/miso/data/util/AuthInterceptor.kt
Labels: ⚡️ Simple, 0️⃣ Priority: Critical

#132 🔀 :: (#131) - fix get list errors
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/ShopViewModel.kt
Labels: 🐞 Bug, 0️⃣ Priority: Critical
