Repository TeamMiso/Miso_Android_v2, pull requests merged in 2024-01, with the labels that each got.

#134 🔀 :: (#133) - fix result list errors
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchableListScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/RecyclablesViewModel.kt
Labels: 🐞 Bug, 0️⃣ Priority: Critical

#135 🔀 :: (#124) - fix inquiry send image bug
  .idea/deploymentTargetDropDown.xml
  presentation/src/main/java/com/miso/presentation/ui/camera/component/CameraPreview.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraCaptureResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/dialog/InquiryDialog.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/CameraViewModel.kt
Labels: 🐞 Bug, 0️⃣ Priority: Critical

#138 (#137) - fix shop detail bug
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopScreen.kt
Labels: 🐞 Bug, ⚡️ Simple, 0️⃣ Priority: Critical

#140 🔀 :: (#139) - prevent multiple click
  design-system/src/main/java/com/miso/design_system/component/button/MisoBackButton.kt
  design-system/src/main/java/com/miso/design_system/component/chip/MisoChip.kt
  design-system/src/main/java/com/miso/design_system/component/modifier/MultipleEventsCutter.kt
  design-system/src/main/java/com/miso/design_system/component/modifier/misoClickable.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryListItem.kt
  presentation/src/main/java/com/miso/presentation/ui/login/component/MoveSignUpText.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/SearchListItem.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/TodayEnvironmentTipComponent.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/component/ShopListItem.kt
Labels: ✨ Feature, 0️⃣ Priority: Critical

#142 (#141) - write the logic get inquiry list
  data/src/main/java/com/miso/data/remote/api/InquiryAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSourceImpl.kt
  data/src/main/java/com/miso/data/repository/InquiryRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/repository/InquiryRepository.kt
  domain/src/main/java/com/miso/domain/usecase/inquiry/GetInquiryListAllUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#144 🔀 :: (#143) - publishing inquiry list filter
  design-system/src/main/java/com/miso/design_system/component/button/ButtonState.kt
  design-system/src/main/java/com/miso/design_system/component/button/MisoButton.kt
  design-system/src/main/res/drawable/ic_filter.xml
  presentation/src/main/java/com/miso/presentation/ui/camera/screen/CameraResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/InquiryListTitleText.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/bottomsheet/SelectFilterBottomSheet.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/login/screen/LoginScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/result/screen/ResultScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/component/TodayEnvironmentTipComponent.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopDetailScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/sign_up/screen/SignUpScreen.kt
Labels: 🎨 Publishing, 1️⃣ Priority: High

#146 🔀 :: (#145) - write the logic inquiry list filter
  data/src/main/java/com/miso/data/remote/api/InquiryAPI.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSource.kt
  data/src/main/java/com/miso/data/remote/datasource/inquiry/InquiryDataSourceImpl.kt
  data/src/main/java/com/miso/data/repository/InquiryRepositoryImpl.kt
  domain/src/main/java/com/miso/domain/repository/InquiryRepository.kt
  domain/src/main/java/com/miso/domain/usecase/inquiry/GetInquiryListFilterUseCase.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/component/bottomsheet/SelectFilterBottomSheet.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High

#148 🔀 :: (#147) - refactoring the initialization function
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/login/screen/LoginScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/ui/search/screen/SearchScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/shop/screen/ShopScreen.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/AuthViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/RecyclablesViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/ShopViewModel.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/UserViewModel.kt
Labels: 🔨 Refector, 3️⃣ Priority: Low

#150 🔀 :: (#149) - pull down to refresh
  presentation/src/main/java/com/miso/presentation/ui/inquiry/screen/InquiryListScreen.kt
  presentation/src/main/java/com/miso/presentation/ui/search/SearchActivity.kt
  presentation/src/main/java/com/miso/presentation/viewmodel/InquiryViewModel.kt
Labels: ✨ Feature, 1️⃣ Priority: High
